resources:
- name: mavcunha-misc
  type: git
  source:
    uri: https://github.com/mavcunha/misc.git
    branch: master
jobs:
  - name: mavcunha-misc-job
    plan:
      - get: mavcunha-misc
      - get: preflight/pre-flight-misc
        trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ubuntu}
          inputs:
            - name: mavcunha-misc
          run:
            path: echo
            args: ['Hello!']
