resources:
- name: mavcunha-misc
  type: git
  source:
    uri: https://github.com/mavcunha/misc.git
    branch: master
jobs:
  - name: mavcunha-misc-build
    plan:
      - get: mavcunha-misc
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ubuntu}
          inputs:
            - name: mavcunha-misc
          run:
            path: mavcunha-misc/concourse/build.sh
            args: ["compile"]
  - name: mavcunha-misc-test
    plan:
      - get: mavcunha-misc
        trigger: true
        passed: [mavcunha-misc-build]
      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ubuntu}
          inputs:
            - name: mavcunha-misc
          run:
            path: mavcunha-misc/concourse/build.sh
            args: ["test"]
